/* Generated by tools/icd_gen.py from docs/icd/flatsat_icd.yaml. Do not edit. */
#ifndef FLATSAT_ICD_H
#define FLATSAT_ICD_H

#include <stdint.h>

#define FLATSAT_ICD_VERSION "1.0"
#define FLATSAT_TLM_HDR_LEN 16
#define FLATSAT_CMD_HDR_LEN 8
#define FLATSAT_RF_MAX_PACKET 249

/* CAN ID = message type << 4 | source node (ICD 6.2) */
#define FLATSAT_CAN_ID(type, node) ((uint16_t)(((type) << 4) | (node)))
#define FLATSAT_CAN_TYPE(id) ((uint8_t)((id) >> 4))
#define FLATSAT_CAN_NODE(id) ((uint8_t)((id) & 0x0F))

/* ---- Enumerations ---- */

/* System mode (ICD 5.1) */
typedef enum
{
    FLATSAT_MODE_SAFE = 0,
    FLATSAT_MODE_DETUMBLE = 1,
    FLATSAT_MODE_SUN_POINT = 2,
    FLATSAT_MODE_LOW_POWER = 3,
    FLATSAT_MODE_TEST = 4,
} flatsat_mode_t;

/* Why the last mode change happened */
typedef enum
{
    FLATSAT_MODE_REASON_BOOT = 0,
    FLATSAT_MODE_REASON_COMMAND = 1,
    FLATSAT_MODE_REASON_FAULT = 2,
    FLATSAT_MODE_REASON_AUTO_RATES_HIGH = 3,
    FLATSAT_MODE_REASON_AUTO_CONVERGED = 4,
    FLATSAT_MODE_REASON_LOW_BATTERY = 5,
    FLATSAT_MODE_REASON_NODE_LOST = 6,
    FLATSAT_MODE_REASON_BATTERY_RECOVERED = 7,
} flatsat_mode_reason_t;

typedef enum
{
    FLATSAT_RESET_CAUSE_POWER_ON = 0,
    FLATSAT_RESET_CAUSE_WATCHDOG = 1,
    FLATSAT_RESET_CAUSE_COMMAND = 2,
    FLATSAT_RESET_CAUSE_UNKNOWN = 3,
} flatsat_reset_cause_t;

typedef enum
{
    FLATSAT_SEVERITY_DEBUG = 0,
    FLATSAT_SEVERITY_INFO = 1,
    FLATSAT_SEVERITY_WARNING = 2,
    FLATSAT_SEVERITY_ERROR = 3,
    FLATSAT_SEVERITY_CRITICAL = 4,
} flatsat_severity_t;

typedef enum
{
    FLATSAT_TIME_SOURCE_FREE_RUNNING = 0,
    FLATSAT_TIME_SOURCE_UMBILICAL = 1,
} flatsat_time_source_t;

typedef enum
{
    FLATSAT_ADCS_MODE_OFF = 0,
    FLATSAT_ADCS_MODE_BDOT = 1,
    FLATSAT_ADCS_MODE_SUN_POINT = 2,
    FLATSAT_ADCS_MODE_MANUAL = 3,
} flatsat_adcs_mode_t;

typedef enum
{
    FLATSAT_CHARGE_STATE_IDLE = 0,
    FLATSAT_CHARGE_STATE_CHARGING = 1,
    FLATSAT_CHARGE_STATE_FULL = 2,
} flatsat_charge_state_t;

typedef enum
{
    FLATSAT_RW_CTRL_MODE_OFF = 0,
    FLATSAT_RW_CTRL_MODE_SPEED = 1,
    FLATSAT_RW_CTRL_MODE_DUTY = 2,
} flatsat_rw_ctrl_mode_t;

typedef enum
{
    FLATSAT_NODE_OBC = 1,
    FLATSAT_NODE_ADCS = 2,
    FLATSAT_NODE_EPS = 3,
} flatsat_node_t;

typedef enum
{
    FLATSAT_NODE_STATE_BOOT = 0,
    FLATSAT_NODE_STATE_NOMINAL = 1,
    FLATSAT_NODE_STATE_SAFE = 2,
    FLATSAT_NODE_STATE_FAULT = 3,
} flatsat_node_state_t;

typedef enum
{
    FLATSAT_NODE_CMD_PING = 1,
    FLATSAT_NODE_CMD_RESET = 2,
    FLATSAT_NODE_CMD_ENTER_SAFE = 3,
} flatsat_node_cmd_t;

typedef enum
{
    FLATSAT_SWITCH_STATE_OFF = 0,
    FLATSAT_SWITCH_STATE_ON = 1,
} flatsat_switch_state_t;

/* ---- Telemetry packets: payload follows the 16-byte header ---- */

/* OBC housekeeping */
#define FLATSAT_OBC_HK_MID 0x0A00
#define FLATSAT_OBC_HK_LEN 52
typedef struct __attribute__((packed))
{
    uint32_t uptime; /* s */
    uint16_t cmd_accept_count;
    uint16_t cmd_reject_count;
    uint16_t last_cmd_mid;
    uint8_t last_cmd_fc;
    uint8_t mode; /* (flatsat_mode_t) */
    uint8_t mode_reason; /* (flatsat_mode_reason_t) */
    uint8_t reset_cause; /* (flatsat_reset_cause_t) */
    uint16_t reset_count;
    uint8_t cpu_load; /* % */
    uint8_t node_alive_mask; /* Bit n set = node n heartbeat seen in the last 3 s */
    uint8_t time_source; /* (flatsat_time_source_t) */
    uint8_t link_flags; /* Bit 0 umbilical up, bit 1 RF contact */
    uint32_t can_tx_count;
    uint32_t can_rx_count;
    uint16_t can_error_count;
    uint8_t can_tec; /* MCP2515 transmit error counter */
    uint8_t can_rec; /* MCP2515 receive error counter */
    uint16_t event_count;
    uint16_t sensor_misses; /* Failed device reads since boot, including isolated misses below the fault persistence threshold */
} flatsat_obc_hk_t;
_Static_assert(sizeof(flatsat_obc_hk_t) == 36, "OBC_HK layout");

/* Compact health beacon, sent over RF every 10 s */
#define FLATSAT_BEACON_MID 0x0A01
#define FLATSAT_BEACON_LEN 36
typedef struct __attribute__((packed))
{
    uint32_t uptime; /* s */
    uint8_t mode; /* (flatsat_mode_t) */
    uint8_t fault_flags;
    uint16_t cmd_accept_count;
    uint16_t sim_batt_mv; /* mV Simulated spacecraft battery (NOS3) */
    uint16_t real_batt_mv; /* mV FlatSat battery (EPS node) */
    uint16_t body_rate; /* mrad/s Estimated body-rate magnitude */
    uint8_t eclipse;
    uint8_t node_alive_mask;
    uint16_t event_count;
    uint16_t spare;
} flatsat_beacon_t;
_Static_assert(sizeof(flatsat_beacon_t) == 20, "BEACON layout");

/* Asynchronous event message */
#define FLATSAT_EVENT_MID 0x0A02
#define FLATSAT_EVENT_LEN 84
typedef struct __attribute__((packed))
{
    uint16_t event_id;
    uint8_t severity; /* (flatsat_severity_t) */
    uint8_t spare;
    char text[64];
} flatsat_event_t;
_Static_assert(sizeof(flatsat_event_t) == 68, "EVENT layout");

/* ADCS estimates and actuator commands */
#define FLATSAT_ADCS_STATE_MID 0x0A10
#define FLATSAT_ADCS_STATE_LEN 100
typedef struct __attribute__((packed))
{
    uint8_t adcs_mode; /* (flatsat_adcs_mode_t) */
    uint8_t sun_valid;
    uint8_t converged;
    uint8_t phys_rw_status; /* Physical wheel RW_TLM status: bit 0 driver enabled, 1 at set point, 2 saturated, 3 command timeout, 4 safe */
    float rate_est[3]; /* rad/s */
    float mag_body[3]; /* T */
    float sun_body[3]; /* Unit vector */
    float pointing_error; /* rad Angle between the +X axis and the Sun; -1 without a Sun vector */
    float rw_cmd_torque[3]; /* N m Torque commanded to the simulated wheels */
    float rw_sim_speed[3]; /* rad/s */
    int16_t trq_duty[3]; /* 0.01 % */
    uint8_t auto_modes; /* 1 = automatic mode transitions enabled (OBC_SET_AUTO_MODES) */
    uint8_t spare2;
    float phys_rw_cmd_speed; /* rad/s */
    float phys_rw_meas_speed; /* rad/s */
} flatsat_adcs_state_t;
_Static_assert(sizeof(flatsat_adcs_state_t) == 84, "ADCS_STATE layout");

/* ADCS sensor readings in SI units */
#define FLATSAT_ADCS_SENSORS_MID 0x0A11
#define FLATSAT_ADCS_SENSORS_LEN 136
typedef struct __attribute__((packed))
{
    uint16_t valid_mask; /* Bit 0 IMU, 1 MAG, 2 FSS, 3 CSS, 4 star tracker, 5 GPS */
    uint16_t spare;
    float imu_rate[3]; /* rad/s */
    float imu_accel[3]; /* m/s2 */
    float mag[3]; /* T */
    float fss_alpha; /* rad */
    float fss_beta; /* rad */
    float css[6]; /* Normalised coarse sun sensor outputs */
    float st_quat[4];
    float gps_pos_ecef[3]; /* m */
    float gps_vel_ecef[3]; /* m/s */
    uint16_t gps_week;
    uint16_t spare2;
    float gps_sow; /* s GPS seconds of week */
} flatsat_adcs_sensors_t;
_Static_assert(sizeof(flatsat_adcs_sensors_t) == 120, "ADCS_SENSORS layout");

/* Simulated spacecraft power (NOS3 EPS sim) */
#define FLATSAT_EPS_SIM_MID 0x0A20
#define FLATSAT_EPS_SIM_LEN 52
typedef struct __attribute__((packed))
{
    float batt_v; /* V */
    float batt_temp; /* degC */
    float bus_3v3; /* V */
    float bus_5v0; /* V */
    float bus_12v; /* V */
    float eps_temp; /* degC */
    float sa_v; /* V */
    float sa_temp; /* degC */
    uint8_t switch_mask;
    uint8_t eclipse;
    uint16_t spare;
} flatsat_eps_sim_t;
_Static_assert(sizeof(flatsat_eps_sim_t) == 36, "EPS_SIM layout");

/* FlatSat measured power (EPS node) */
#define FLATSAT_EPS_REAL_MID 0x0A21
#define FLATSAT_EPS_REAL_LEN 48
typedef struct __attribute__((packed))
{
    uint16_t rail_mv[3]; /* mV Rail 0 battery out, 1 OBC + radio, 2 ADCS node */
    int16_t rail_ma[3]; /* mA */
    uint16_t rail_mw[3]; /* mW */
    uint16_t batt_mv; /* mV */
    int16_t batt_ma; /* mA */
    uint8_t charge_state; /* (flatsat_charge_state_t) */
    uint8_t switch_mask; /* Bit 0 ADCS node supply, bit 1 wheel motor supply */
    uint8_t switch_fault_mask;
    uint8_t eps_node_state; /* (flatsat_node_state_t) */
    uint16_t spare;
    uint32_t eps_uptime; /* s */
} flatsat_eps_real_t;
_Static_assert(sizeof(flatsat_eps_real_t) == 32, "EPS_REAL layout");

/* RF and umbilical link statistics */
#define FLATSAT_COMMS_STATS_MID 0x0A30
#define FLATSAT_COMMS_STATS_LEN 44
typedef struct __attribute__((packed))
{
    uint32_t rf_tx_frames;
    uint32_t rf_rx_frames;
    uint16_t rf_crc_errors;
    uint16_t rf_rejected;
    int16_t last_rssi; /* dBm */
    int8_t last_snr; /* 0.25 dB */
    uint8_t contact;
    uint16_t duty_cycle; /* 0.1 % Airtime used in the last hour */
    uint16_t tx_queue_depth;
    uint32_t umb_tx_packets;
    uint32_t umb_rx_packets;
} flatsat_comms_stats_t;
_Static_assert(sizeof(flatsat_comms_stats_t) == 28, "COMMS_STATS layout");

/* Reply to OBC_PING, for latency measurement */
#define FLATSAT_PING_REPLY_MID 0x0A31
#define FLATSAT_PING_REPLY_LEN 28
typedef struct __attribute__((packed))
{
    uint32_t token;
    uint32_t rx_seconds; /* s OBC time when the ping was received */
    uint16_t rx_subseconds; /* 2^-16 s */
    uint16_t spare;
} flatsat_ping_reply_t;
_Static_assert(sizeof(flatsat_ping_reply_t) == 12, "PING_REPLY layout");

/* ---- Commands: arguments follow the 8-byte header ---- */

#define FLATSAT_OBC_CMD_MID 0x1A00
#define FLATSAT_ADCS_CMD_MID 0x1A10
#define FLATSAT_EPS_CMD_MID 0x1A20
#define FLATSAT_COMMS_CMD_MID 0x1A30

#define FLATSAT_OBC_NOOP_FC 0
#define FLATSAT_OBC_NOOP_LEN 8

#define FLATSAT_OBC_RESET_COUNTERS_FC 1
#define FLATSAT_OBC_RESET_COUNTERS_LEN 8

#define FLATSAT_OBC_SET_MODE_FC 2
#define FLATSAT_OBC_SET_MODE_LEN 9
typedef struct __attribute__((packed))
{
    uint8_t mode; /* (flatsat_mode_t) */
} flatsat_obc_set_mode_t;
_Static_assert(sizeof(flatsat_obc_set_mode_t) == 1, "OBC_SET_MODE layout");

#define FLATSAT_OBC_SET_TIME_FC 3
#define FLATSAT_OBC_SET_TIME_LEN 14
typedef struct __attribute__((packed))
{
    uint32_t seconds; /* s */
    uint16_t subseconds; /* 2^-16 s */
} flatsat_obc_set_time_t;
_Static_assert(sizeof(flatsat_obc_set_time_t) == 6, "OBC_SET_TIME layout");

#define FLATSAT_OBC_PING_FC 4
#define FLATSAT_OBC_PING_LEN 12
typedef struct __attribute__((packed))
{
    uint32_t token;
} flatsat_obc_ping_t;
_Static_assert(sizeof(flatsat_obc_ping_t) == 4, "OBC_PING layout");

#define FLATSAT_OBC_SET_TLM_PERIOD_FC 5
#define FLATSAT_OBC_SET_TLM_PERIOD_LEN 12
typedef struct __attribute__((packed))
{
    uint16_t tlm_mid;
    uint16_t period; /* ms 0 = off */
} flatsat_obc_set_tlm_period_t;
_Static_assert(sizeof(flatsat_obc_set_tlm_period_t) == 4, "OBC_SET_TLM_PERIOD layout");

#define FLATSAT_OBC_DOWNLINK_PACKET_FC 6
#define FLATSAT_OBC_DOWNLINK_PACKET_LEN 10
typedef struct __attribute__((packed))
{
    uint16_t tlm_mid;
} flatsat_obc_downlink_packet_t;
_Static_assert(sizeof(flatsat_obc_downlink_packet_t) == 2, "OBC_DOWNLINK_PACKET layout");

#define FLATSAT_OBC_NODE_RESET_FC 7
#define FLATSAT_OBC_NODE_RESET_LEN 9
typedef struct __attribute__((packed))
{
    uint8_t node; /* (flatsat_node_t) */
} flatsat_obc_node_reset_t;
_Static_assert(sizeof(flatsat_obc_node_reset_t) == 1, "OBC_NODE_RESET layout");

#define FLATSAT_OBC_REBOOT_FC 8
#define FLATSAT_OBC_REBOOT_LEN 12
typedef struct __attribute__((packed))
{
    uint32_t magic; /* Must be 0x0B0075ED */
} flatsat_obc_reboot_t;
_Static_assert(sizeof(flatsat_obc_reboot_t) == 4, "OBC_REBOOT layout");

#define FLATSAT_OBC_SET_AUTO_MODES_FC 9
#define FLATSAT_OBC_SET_AUTO_MODES_LEN 9
typedef struct __attribute__((packed))
{
    uint8_t state; /* (flatsat_switch_state_t) */
} flatsat_obc_set_auto_modes_t;
_Static_assert(sizeof(flatsat_obc_set_auto_modes_t) == 1, "OBC_SET_AUTO_MODES layout");

#define FLATSAT_ADCS_NOOP_FC 0
#define FLATSAT_ADCS_NOOP_LEN 8

#define FLATSAT_ADCS_SET_BDOT_GAIN_FC 1
#define FLATSAT_ADCS_SET_BDOT_GAIN_LEN 12
typedef struct __attribute__((packed))
{
    float gain; /* A m2 s m = -gain dB/dt / |B|; 0 < gain <= 10000 */
} flatsat_adcs_set_bdot_gain_t;
_Static_assert(sizeof(flatsat_adcs_set_bdot_gain_t) == 4, "ADCS_SET_BDOT_GAIN layout");

#define FLATSAT_ADCS_SET_SUN_GAINS_FC 2
#define FLATSAT_ADCS_SET_SUN_GAINS_LEN 16
typedef struct __attribute__((packed))
{
    float kp; /* 1/s2 wn^2, inertia-normalised */
    float kd; /* 1/s 2 zeta wn */
} flatsat_adcs_set_sun_gains_t;
_Static_assert(sizeof(flatsat_adcs_set_sun_gains_t) == 8, "ADCS_SET_SUN_GAINS layout");

#define FLATSAT_ADCS_RW_MANUAL_FC 3
#define FLATSAT_ADCS_RW_MANUAL_LEN 16
typedef struct __attribute__((packed))
{
    uint8_t wheel;
    uint8_t spare;
    uint16_t spare2;
    float speed; /* rad/s */
} flatsat_adcs_rw_manual_t;
_Static_assert(sizeof(flatsat_adcs_rw_manual_t) == 8, "ADCS_RW_MANUAL layout");

#define FLATSAT_ADCS_TRQ_MANUAL_FC 4
#define FLATSAT_ADCS_TRQ_MANUAL_LEN 12
typedef struct __attribute__((packed))
{
    uint8_t torquer;
    uint8_t spare;
    int16_t duty; /* 0.01 % */
} flatsat_adcs_trq_manual_t;
_Static_assert(sizeof(flatsat_adcs_trq_manual_t) == 4, "ADCS_TRQ_MANUAL layout");

#define FLATSAT_ADCS_PHYS_WHEEL_TEST_FC 5
#define FLATSAT_ADCS_PHYS_WHEEL_TEST_LEN 12
typedef struct __attribute__((packed))
{
    uint8_t ctrl_mode; /* (flatsat_rw_ctrl_mode_t) */
    uint8_t spare;
    int16_t setpoint; /* rpm (SPEED) or 0.01 % (DUTY) */
} flatsat_adcs_phys_wheel_test_t;
_Static_assert(sizeof(flatsat_adcs_phys_wheel_test_t) == 4, "ADCS_PHYS_WHEEL_TEST layout");

#define FLATSAT_EPS_NOOP_FC 0
#define FLATSAT_EPS_NOOP_LEN 8

#define FLATSAT_EPS_SWITCH_FC 1
#define FLATSAT_EPS_SWITCH_LEN 10
typedef struct __attribute__((packed))
{
    uint8_t switch_id;
    uint8_t state; /* (flatsat_switch_state_t) */
} flatsat_eps_switch_t;
_Static_assert(sizeof(flatsat_eps_switch_t) == 2, "EPS_SWITCH layout");

#define FLATSAT_EPS_SIM_SWITCH_FC 2
#define FLATSAT_EPS_SIM_SWITCH_LEN 10
typedef struct __attribute__((packed))
{
    uint8_t switch_id;
    uint8_t state; /* (flatsat_switch_state_t) */
} flatsat_eps_sim_switch_t;
_Static_assert(sizeof(flatsat_eps_sim_switch_t) == 2, "EPS_SIM_SWITCH layout");

#define FLATSAT_COMMS_NOOP_FC 0
#define FLATSAT_COMMS_NOOP_LEN 8

#define FLATSAT_COMMS_SET_TX_POWER_FC 1
#define FLATSAT_COMMS_SET_TX_POWER_LEN 9
typedef struct __attribute__((packed))
{
    int8_t power; /* dBm */
} flatsat_comms_set_tx_power_t;
_Static_assert(sizeof(flatsat_comms_set_tx_power_t) == 1, "COMMS_SET_TX_POWER layout");

#define FLATSAT_COMMS_SET_BEACON_PERIOD_FC 2
#define FLATSAT_COMMS_SET_BEACON_PERIOD_LEN 10
typedef struct __attribute__((packed))
{
    uint16_t period; /* s */
} flatsat_comms_set_beacon_period_t;
_Static_assert(sizeof(flatsat_comms_set_beacon_period_t) == 2, "COMMS_SET_BEACON_PERIOD layout");

/* ---- CAN messages (ICD 6.3) ---- */

/* TIME_SYNC: from OBC, every 1000 ms */
#define FLATSAT_CAN_TIME_SYNC_TYPE 0x01
#define FLATSAT_CAN_TIME_SYNC_DLC 6
#define FLATSAT_CAN_TIME_SYNC_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint32_t seconds; /* s */
    uint16_t subseconds; /* 2^-16 s */
} flatsat_can_time_sync_t;
_Static_assert(sizeof(flatsat_can_time_sync_t) == 6, "CAN TIME_SYNC layout");

/* MODE: from OBC, every 1000 ms */
#define FLATSAT_CAN_MODE_TYPE 0x02
#define FLATSAT_CAN_MODE_DLC 2
#define FLATSAT_CAN_MODE_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint8_t mode; /* (flatsat_mode_t) */
    uint8_t flags;
} flatsat_can_mode_t;
_Static_assert(sizeof(flatsat_can_mode_t) == 2, "CAN MODE layout");

/* FAULT: from any node, on event */
#define FLATSAT_CAN_FAULT_TYPE 0x04
#define FLATSAT_CAN_FAULT_DLC 4
#define FLATSAT_CAN_FAULT_PERIOD_MS 0
typedef struct __attribute__((packed))
{
    uint8_t code;
    uint8_t detail;
    uint16_t value;
} flatsat_can_fault_t;
_Static_assert(sizeof(flatsat_can_fault_t) == 4, "CAN FAULT layout");

/* RW_CMD: from OBC, every 100 ms */
#define FLATSAT_CAN_RW_CMD_TYPE 0x10
#define FLATSAT_CAN_RW_CMD_DLC 5
#define FLATSAT_CAN_RW_CMD_PERIOD_MS 100
typedef struct __attribute__((packed))
{
    uint8_t wheel;
    uint8_t ctrl_mode; /* (flatsat_rw_ctrl_mode_t) */
    int16_t setpoint; /* rpm (SPEED) or 0.01 % (DUTY) */
    uint8_t seq;
} flatsat_can_rw_cmd_t;
_Static_assert(sizeof(flatsat_can_rw_cmd_t) == 5, "CAN RW_CMD layout");

/* RW_TLM: from ADCS, every 100 ms */
#define FLATSAT_CAN_RW_TLM_TYPE 0x11
#define FLATSAT_CAN_RW_TLM_DLC 8
#define FLATSAT_CAN_RW_TLM_PERIOD_MS 100
typedef struct __attribute__((packed))
{
    uint8_t wheel;
    uint8_t status;
    int16_t speed; /* rpm */
    int16_t setpoint_echo;
    int8_t duty; /* % */
    uint8_t seq_echo;
} flatsat_can_rw_tlm_t;
_Static_assert(sizeof(flatsat_can_rw_tlm_t) == 8, "CAN RW_TLM layout");

/* EPS_RAIL: from EPS, every 1000 ms */
#define FLATSAT_CAN_EPS_RAIL_TYPE 0x20
#define FLATSAT_CAN_EPS_RAIL_DLC 8
#define FLATSAT_CAN_EPS_RAIL_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint8_t rail;
    uint8_t flags;
    uint16_t voltage; /* mV */
    int16_t current; /* mA */
    uint16_t power; /* mW */
} flatsat_can_eps_rail_t;
_Static_assert(sizeof(flatsat_can_eps_rail_t) == 8, "CAN EPS_RAIL layout");

/* EPS_BATT: from EPS, every 1000 ms */
#define FLATSAT_CAN_EPS_BATT_TYPE 0x21
#define FLATSAT_CAN_EPS_BATT_DLC 6
#define FLATSAT_CAN_EPS_BATT_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint16_t voltage; /* mV */
    int16_t current; /* mA */
    uint8_t charge_state; /* (flatsat_charge_state_t) */
    uint8_t flags;
} flatsat_can_eps_batt_t;
_Static_assert(sizeof(flatsat_can_eps_batt_t) == 6, "CAN EPS_BATT layout");

/* EPS_SW_CMD: from OBC, on event */
#define FLATSAT_CAN_EPS_SW_CMD_TYPE 0x28
#define FLATSAT_CAN_EPS_SW_CMD_DLC 3
#define FLATSAT_CAN_EPS_SW_CMD_PERIOD_MS 0
typedef struct __attribute__((packed))
{
    uint8_t switch_id;
    uint8_t state; /* (flatsat_switch_state_t) */
    uint8_t seq;
} flatsat_can_eps_sw_cmd_t;
_Static_assert(sizeof(flatsat_can_eps_sw_cmd_t) == 3, "CAN EPS_SW_CMD layout");

/* EPS_SW_TLM: from EPS, every 1000 ms */
#define FLATSAT_CAN_EPS_SW_TLM_TYPE 0x29
#define FLATSAT_CAN_EPS_SW_TLM_DLC 3
#define FLATSAT_CAN_EPS_SW_TLM_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint8_t state_mask;
    uint8_t fault_mask;
    uint8_t seq_echo;
} flatsat_can_eps_sw_tlm_t;
_Static_assert(sizeof(flatsat_can_eps_sw_tlm_t) == 3, "CAN EPS_SW_TLM layout");

/* HEARTBEAT: from any node, every 1000 ms */
#define FLATSAT_CAN_HEARTBEAT_TYPE 0x70
#define FLATSAT_CAN_HEARTBEAT_DLC 8
#define FLATSAT_CAN_HEARTBEAT_PERIOD_MS 1000
typedef struct __attribute__((packed))
{
    uint32_t uptime; /* s */
    uint8_t state; /* (flatsat_node_state_t) */
    uint8_t tec;
    uint8_t rec;
    uint8_t reset_cause; /* (flatsat_reset_cause_t) */
} flatsat_can_heartbeat_t;
_Static_assert(sizeof(flatsat_can_heartbeat_t) == 8, "CAN HEARTBEAT layout");

/* NODE_CMD: from OBC, on event */
#define FLATSAT_CAN_NODE_CMD_TYPE 0x7E
#define FLATSAT_CAN_NODE_CMD_DLC 4
#define FLATSAT_CAN_NODE_CMD_PERIOD_MS 0
typedef struct __attribute__((packed))
{
    uint8_t target; /* (flatsat_node_t) */
    uint8_t cmd; /* (flatsat_node_cmd_t) */
    uint16_t arg;
} flatsat_can_node_cmd_t;
_Static_assert(sizeof(flatsat_can_node_cmd_t) == 4, "CAN NODE_CMD layout");

/* NODE_ACK: from any node, on event */
#define FLATSAT_CAN_NODE_ACK_TYPE 0x7F
#define FLATSAT_CAN_NODE_ACK_DLC 2
#define FLATSAT_CAN_NODE_ACK_PERIOD_MS 0
typedef struct __attribute__((packed))
{
    uint8_t cmd; /* (flatsat_node_cmd_t) */
    uint8_t result;
} flatsat_can_node_ack_t;
_Static_assert(sizeof(flatsat_can_node_ack_t) == 2, "CAN NODE_ACK layout");

/* ---- Tables for dispatchers and schedulers ---- */
/* X(name, mid, total_len) */
#define FLATSAT_TLM_LIST(X) \
    X(OBC_HK, 0x0A00, 52) \
    X(BEACON, 0x0A01, 36) \
    X(EVENT, 0x0A02, 84) \
    X(ADCS_STATE, 0x0A10, 100) \
    X(ADCS_SENSORS, 0x0A11, 136) \
    X(EPS_SIM, 0x0A20, 52) \
    X(EPS_REAL, 0x0A21, 48) \
    X(COMMS_STATS, 0x0A30, 44) \
    X(PING_REPLY, 0x0A31, 28) \

/* X(name, mid, fc, total_len) */
#define FLATSAT_CMD_LIST(X) \
    X(OBC_NOOP, 0x1A00, 0, 8) \
    X(OBC_RESET_COUNTERS, 0x1A00, 1, 8) \
    X(OBC_SET_MODE, 0x1A00, 2, 9) \
    X(OBC_SET_TIME, 0x1A00, 3, 14) \
    X(OBC_PING, 0x1A00, 4, 12) \
    X(OBC_SET_TLM_PERIOD, 0x1A00, 5, 12) \
    X(OBC_DOWNLINK_PACKET, 0x1A00, 6, 10) \
    X(OBC_NODE_RESET, 0x1A00, 7, 9) \
    X(OBC_REBOOT, 0x1A00, 8, 12) \
    X(OBC_SET_AUTO_MODES, 0x1A00, 9, 9) \
    X(ADCS_NOOP, 0x1A10, 0, 8) \
    X(ADCS_SET_BDOT_GAIN, 0x1A10, 1, 12) \
    X(ADCS_SET_SUN_GAINS, 0x1A10, 2, 16) \
    X(ADCS_RW_MANUAL, 0x1A10, 3, 16) \
    X(ADCS_TRQ_MANUAL, 0x1A10, 4, 12) \
    X(ADCS_PHYS_WHEEL_TEST, 0x1A10, 5, 12) \
    X(EPS_NOOP, 0x1A20, 0, 8) \
    X(EPS_SWITCH, 0x1A20, 1, 10) \
    X(EPS_SIM_SWITCH, 0x1A20, 2, 10) \
    X(COMMS_NOOP, 0x1A30, 0, 8) \
    X(COMMS_SET_TX_POWER, 0x1A30, 1, 9) \
    X(COMMS_SET_BEACON_PERIOD, 0x1A30, 2, 10) \

/* X(name, type, dlc, period_ms) */
#define FLATSAT_CAN_LIST(X) \
    X(TIME_SYNC, 0x01, 6, 1000) \
    X(MODE, 0x02, 2, 1000) \
    X(FAULT, 0x04, 4, 0) \
    X(RW_CMD, 0x10, 5, 100) \
    X(RW_TLM, 0x11, 8, 100) \
    X(EPS_RAIL, 0x20, 8, 1000) \
    X(EPS_BATT, 0x21, 6, 1000) \
    X(EPS_SW_CMD, 0x28, 3, 0) \
    X(EPS_SW_TLM, 0x29, 3, 1000) \
    X(HEARTBEAT, 0x70, 8, 1000) \
    X(NODE_CMD, 0x7E, 4, 0) \
    X(NODE_ACK, 0x7F, 2, 0) \

#endif /* FLATSAT_ICD_H */
