#!/usr/bin/env python3
"""Generate interface artefacts from docs/icd/flatsat_icd.yaml.

Outputs (all marked "generated, do not edit"):
    firmware/common/include/flatsat_icd.h       C structs, IDs, lengths, X-macro tables
    ground/flatsat_icd.py                       Python codec for ground software and tests
    nos3/components/hil_bridge/gsw/FLATSAT/cmd_tlm/FLATSAT_TLM.txt
    nos3/components/hil_bridge/gsw/FLATSAT/cmd_tlm/FLATSAT_CMD.txt
                                                COSMOS 4 packet definitions (NOS3's COSMOS build copies
                                                components/*/gsw into its configuration)
    docs/icd/ICD_layouts.md                     Byte-level layout tables

Usage:
    python3 tools/icd_gen.py           regenerate
    python3 tools/icd_gen.py --check   exit 1 if any generated file is out of date (for CI)
"""
import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/icd/flatsat_icd.yaml"

TLM_HDR_LEN = 16
CMD_HDR_LEN = 8
RF_MAX_PACKET = 249
CAN_MAX_DLC = 8

# type -> (size, C type, struct code, COSMOS type, signed)
TYPES = {
    "u8": (1, "uint8_t", "B", "UINT", False),
    "u16": (2, "uint16_t", "H", "UINT", False),
    "u32": (4, "uint32_t", "I", "UINT", False),
    "i8": (1, "int8_t", "b", "INT", True),
    "i16": (2, "int16_t", "h", "INT", True),
    "i32": (4, "int32_t", "i", "INT", True),
    "f32": (4, "float", "f", "FLOAT", True),
    "char": (1, "char", "s", "STRING", False),
}

HEADER_NOTE = "Generated by tools/icd_gen.py from docs/icd/flatsat_icd.yaml. Do not edit."

# Field names become C struct members and Python identifiers, so neither language's keywords are allowed
RESERVED = {
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else", "enum", "extern",
    "float", "for", "goto", "if", "inline", "int", "long", "register", "restrict", "return", "short", "signed",
    "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned", "void", "volatile", "while", "bool",
    "and", "as", "assert", "async", "await", "class", "def", "del", "elif", "except", "finally", "from",
    "global", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "try", "with", "yield",
}


class IcdError(Exception):
    pass


# ---------------------------------------------------------------------------
# Loading and validation
# ---------------------------------------------------------------------------

def layout(fields, where):
    """Return fields with offsets and sizes; enforce natural alignment."""
    out = []
    offset = 0
    for f in fields or []:
        if f["name"].lower() in RESERVED:
            raise IcdError(f"{where}.{f['name']}: field name is a C or Python keyword")
        if f["type"] not in TYPES:
            raise IcdError(f"{where}.{f['name']}: unknown type {f['type']}")
        size, *_ = TYPES[f["type"]]
        count = f.get("count", 1)
        if f["type"] == "char" and "count" not in f:
            raise IcdError(f"{where}.{f['name']}: char fields need a count")
        if offset % size:
            raise IcdError(f"{where}.{f['name']}: offset {offset} is not aligned to {size} bytes; "
                           f"add a spare field before it")
        out.append(dict(f, offset=offset, size=size * count, count=count))
        offset += size * count
    return out, offset


def load(path=SOURCE):
    data = yaml.safe_load(path.read_text())
    enums = data["enums"]

    # YAML 1.1 turns unquoted OFF/ON/YES/NO into booleans ("Norway problem"); names must be identifiers
    for ename, e in enums.items():
        for key in e["values"]:
            if not isinstance(key, str) or not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
                raise IcdError(f"enum {ename}: value name {key!r} must be an UPPER_CASE identifier "
                               f"(quote OFF/ON/YES/NO in the YAML)")

    def check_enums(fields, where):
        for f in fields:
            if "enum" in f and f["enum"] not in enums:
                raise IcdError(f"{where}.{f['name']}: unknown enum {f['enum']}")

    mids = {}
    tlm = []
    for p in data["telemetry"]:
        fields, size = layout(p["fields"], p["name"])
        check_enums(fields, p["name"])
        if not 0x0800 <= p["mid"] <= 0x0FFF:
            raise IcdError(f"{p['name']}: telemetry MID 0x{p['mid']:04X} must have the TM type bit clear")
        if p["mid"] in mids:
            raise IcdError(f"{p['name']}: MID 0x{p['mid']:04X} already used by {mids[p['mid']]}")
        mids[p["mid"]] = p["name"]
        total = TLM_HDR_LEN + size
        if total > RF_MAX_PACKET:
            raise IcdError(f"{p['name']}: {total} bytes exceeds the RF packet limit of {RF_MAX_PACKET}")
        tlm.append(dict(p, fields=fields, payload_len=size, total_len=total))

    cmds = []
    for group in data["commands"]:
        if not 0x1800 <= group["mid"] <= 0x1FFF:
            raise IcdError(f"{group['prefix']}: command MID 0x{group['mid']:04X} must have the TC type bit set")
        if group["mid"] in mids:
            raise IcdError(f"{group['prefix']}: MID 0x{group['mid']:04X} already used by {mids[group['mid']]}")
        mids[group["mid"]] = group["prefix"]
        fcs = set()
        for c in group["commands"]:
            name = f"{group['prefix']}_{c['name']}"
            if c["fc"] in fcs:
                raise IcdError(f"{name}: function code {c['fc']} used twice in MID 0x{group['mid']:04X}")
            fcs.add(c["fc"])
            fields, size = layout(c.get("fields"), name)
            check_enums(fields, name)
            total = CMD_HDR_LEN + size
            if total > RF_MAX_PACKET:
                raise IcdError(f"{name}: {total} bytes exceeds the RF packet limit")
            cmds.append(dict(c, name=name, short=c["name"], prefix=group["prefix"], mid=group["mid"],
                             fields=fields, payload_len=size, total_len=total, desc=c.get("desc", "")))

    can = []
    types = {}
    for m in data["can"]:
        fields, size = layout(m["fields"], f"CAN {m['name']}")
        check_enums(fields, m["name"])
        if size > CAN_MAX_DLC:
            raise IcdError(f"CAN {m['name']}: {size} bytes exceeds {CAN_MAX_DLC}")
        if not 0 < m["type"] < 0x80:
            raise IcdError(f"CAN {m['name']}: type must be 1..127")
        if m["type"] in types:
            raise IcdError(f"CAN {m['name']}: type 0x{m['type']:02X} already used by {types[m['type']]}")
        types[m["type"]] = m["name"]
        if m["src"] != "ANY" and m["src"] not in enums["node"]["values"]:
            raise IcdError(f"CAN {m['name']}: unknown source node {m['src']}")
        can.append(dict(m, fields=fields, dlc=size))

    return dict(version=data["version"], enums=enums, tlm=tlm, cmds=cmds, can=can)


# ---------------------------------------------------------------------------
# C header
# ---------------------------------------------------------------------------

def c_fields(fields):
    lines = []
    for f in fields:
        _, ctype, *_ = TYPES[f["type"]]
        arr = f"[{f['count']}]" if f["count"] > 1 or f["type"] == "char" else ""
        note = " ".join(x for x in [f.get("units", ""), f.get("desc", "")] if x)
        if "enum" in f:
            note = (note + f" (flatsat_{f['enum']}_t)").strip()
        comment = f" /* {note} */" if note else ""
        lines.append(f"    {ctype} {f['name'].lower()}{arr};{comment}")
    return lines


def gen_c(icd):
    o = [f"/* {HEADER_NOTE} */",
         "#ifndef FLATSAT_ICD_H", "#define FLATSAT_ICD_H", "",
         "#include <stdint.h>", "",
         f'#define FLATSAT_ICD_VERSION "{icd["version"]}"',
         f"#define FLATSAT_TLM_HDR_LEN {TLM_HDR_LEN}",
         f"#define FLATSAT_CMD_HDR_LEN {CMD_HDR_LEN}",
         f"#define FLATSAT_RF_MAX_PACKET {RF_MAX_PACKET}", "",
         "/* CAN ID = message type << 4 | source node (ICD 6.2) */",
         "#define FLATSAT_CAN_ID(type, node) ((uint16_t)(((type) << 4) | (node)))",
         "#define FLATSAT_CAN_TYPE(id) ((uint8_t)((id) >> 4))",
         "#define FLATSAT_CAN_NODE(id) ((uint8_t)((id) & 0x0F))", "",
         "/* ---- Enumerations ---- */", ""]
    for name, e in icd["enums"].items():
        if e.get("desc"):
            o.append(f"/* {e['desc']} */")
        o.append("typedef enum")
        o.append("{")
        for k, v in e["values"].items():
            o.append(f"    FLATSAT_{name.upper()}_{k} = {v},")
        o.append(f"}} flatsat_{name}_t;")
        o.append("")

    o += ["/* ---- Telemetry packets: payload follows the 16-byte header ---- */", ""]
    for p in icd["tlm"]:
        n = p["name"]
        o.append(f"/* {p['desc']} */")
        o.append(f"#define FLATSAT_{n}_MID 0x{p['mid']:04X}")
        o.append(f"#define FLATSAT_{n}_LEN {p['total_len']}")
        o.append("typedef struct __attribute__((packed))")
        o.append("{")
        o += c_fields(p["fields"])
        o.append(f"}} flatsat_{n.lower()}_t;")
        o.append(f'_Static_assert(sizeof(flatsat_{n.lower()}_t) == {p["payload_len"]}, "{n} layout");')
        o.append("")

    o += ["/* ---- Commands: arguments follow the 8-byte header ---- */", ""]
    for group in sorted({(c["prefix"], c["mid"]) for c in icd["cmds"]}, key=lambda g: g[1]):
        o.append(f"#define FLATSAT_{group[0]}_CMD_MID 0x{group[1]:04X}")
    o.append("")
    for c in icd["cmds"]:
        n = c["name"]
        o.append(f"#define FLATSAT_{n}_FC {c['fc']}")
        o.append(f"#define FLATSAT_{n}_LEN {c['total_len']}")
        if c["fields"]:
            o.append("typedef struct __attribute__((packed))")
            o.append("{")
            o += c_fields(c["fields"])
            o.append(f"}} flatsat_{n.lower()}_t;")
            o.append(f'_Static_assert(sizeof(flatsat_{n.lower()}_t) == {c["payload_len"]}, "{n} layout");')
        o.append("")

    o += ["/* ---- CAN messages (ICD 6.3) ---- */", ""]
    for m in icd["can"]:
        n = m["name"]
        src = "any node" if m["src"] == "ANY" else m["src"]
        period = f"every {m['period_ms']} ms" if m["period_ms"] else "on event"
        o.append(f"/* {n}: from {src}, {period} */")
        o.append(f"#define FLATSAT_CAN_{n}_TYPE 0x{m['type']:02X}")
        o.append(f"#define FLATSAT_CAN_{n}_DLC {m['dlc']}")
        o.append(f"#define FLATSAT_CAN_{n}_PERIOD_MS {m['period_ms']}")
        o.append("typedef struct __attribute__((packed))")
        o.append("{")
        o += c_fields(m["fields"])
        o.append(f"}} flatsat_can_{n.lower()}_t;")
        o.append(f'_Static_assert(sizeof(flatsat_can_{n.lower()}_t) == {m["dlc"]}, "CAN {n} layout");')
        o.append("")

    o += ["/* ---- Tables for dispatchers and schedulers ---- */",
          "/* X(name, mid, total_len) */",
          "#define FLATSAT_TLM_LIST(X) \\"]
    o += [f"    X({p['name']}, 0x{p['mid']:04X}, {p['total_len']}) \\" for p in icd["tlm"]]
    o += ["", "/* X(name, mid, fc, total_len) */", "#define FLATSAT_CMD_LIST(X) \\"]
    o += [f"    X({c['name']}, 0x{c['mid']:04X}, {c['fc']}, {c['total_len']}) \\" for c in icd["cmds"]]
    o += ["", "/* X(name, type, dlc, period_ms) */", "#define FLATSAT_CAN_LIST(X) \\"]
    o += [f"    X({m['name']}, 0x{m['type']:02X}, {m['dlc']}, {m['period_ms']}) \\" for m in icd["can"]]
    o += ["", "#endif /* FLATSAT_ICD_H */", ""]
    return "\n".join(o)


# ---------------------------------------------------------------------------
# COSMOS 4 definitions
# ---------------------------------------------------------------------------

def cosmos_desc(f):
    return (f.get("desc") or f["name"].replace("_", " ").capitalize()).replace('"', "'")


def cosmos_items(fields, enums, command):
    lines = []
    for f in fields:
        size, _, _, ctype, signed = TYPES[f["type"]]
        names = [f["name"]] if f["count"] == 1 or f["type"] == "char" else \
            [f"{f['name']}_{i}" for i in range(f["count"])]
        bits = size * 8 * (f["count"] if f["type"] == "char" else 1)
        for nm in names:
            if command:
                if ctype == "FLOAT":
                    rng = "MIN_FLOAT32 MAX_FLOAT32 0.0"
                else:
                    lim = f"{'' if signed else 'U'}INT{bits}"
                    rng = f"MIN_{lim} MAX_{lim} 0"
                lines.append(f'  APPEND_PARAMETER {nm} {bits} {ctype} {rng} "{cosmos_desc(f)}"')
            else:
                lines.append(f'  APPEND_ITEM {nm} {bits} {ctype} "{cosmos_desc(f)}"')
            if f.get("units"):
                lines.append(f'    UNITS "{f["units"]}" "{f["units"]}"')
            if "enum" in f:
                for k, v in enums[f["enum"]]["values"].items():
                    lines.append(f"    STATE {k} {v}")
    return lines


def gen_cosmos_tlm(icd):
    o = [f"# {HEADER_NOTE}", ""]
    for p in icd["tlm"]:
        o += [f'TELEMETRY FLATSAT {p["name"]} LITTLE_ENDIAN "{p["desc"]}"',
              f'  APPEND_ID_ITEM CCSDS_STREAMID 16 UINT 0x{p["mid"]:04X} "CCSDS packet identification" BIG_ENDIAN',
              '  APPEND_ITEM CCSDS_SEQUENCE 16 UINT "CCSDS packet sequence control" BIG_ENDIAN',
              '  APPEND_ITEM CCSDS_LENGTH 16 UINT "CCSDS packet data length" BIG_ENDIAN',
              '  APPEND_ITEM CCSDS_SECONDS 32 UINT "Time: seconds since J2000" BIG_ENDIAN',
              '  APPEND_ITEM CCSDS_SUBSECS 16 UINT "Time: subseconds (2^-16 s)" BIG_ENDIAN',
              '  APPEND_ITEM CCSDS_SPARE 32 UINT "Header spare"']
        o += cosmos_items(p["fields"], icd["enums"], command=False)
        o.append("")
    return "\n".join(o)


def gen_cosmos_cmd(icd):
    o = [f"# {HEADER_NOTE}",
         "# CCSDS_CHECKSUM must make the XOR of all packet bytes equal 0xFF (ICD 3.2);",
         "# the FlatSat interfaces fill it in with lib/flatsat_checksum_protocol.rb.", ""]
    for c in icd["cmds"]:
        o += [f'COMMAND FLATSAT {c["name"]} LITTLE_ENDIAN "{c["desc"] or c["name"]}"',
              f'  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN_UINT16 MAX_UINT16 0x{c["mid"]:04X} '
              f'"CCSDS packet identification" BIG_ENDIAN',
              '  APPEND_PARAMETER CCSDS_SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 '
              '"CCSDS packet sequence control" BIG_ENDIAN',
              f'  APPEND_PARAMETER CCSDS_LENGTH 16 UINT MIN_UINT16 MAX_UINT16 {c["total_len"] - 7} '
              f'"CCSDS packet data length" BIG_ENDIAN',
              f'  APPEND_ID_PARAMETER CCSDS_FC 8 UINT MIN_UINT8 MAX_UINT8 {c["fc"]} "Function code"',
              '  APPEND_PARAMETER CCSDS_CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 0 "Command checksum"']
        o += cosmos_items(c["fields"], icd["enums"], command=True)
        o.append("")
    return "\n".join(o)


# ---------------------------------------------------------------------------
# Python codec
# ---------------------------------------------------------------------------

def py_fmt(fields):
    fmt = "<"
    names = []
    for f in fields:
        code = TYPES[f["type"]][2]
        if f["type"] == "char":
            fmt += f"{f['count']}s"
            names.append(f["name"])
        else:
            fmt += code * f["count"]
            names += [f["name"]] if f["count"] == 1 else [f"{f['name']}_{i}" for i in range(f["count"])]
    return fmt, names


PY_RUNTIME = '''
TLM_HEADER = struct.Struct(">HHHIHI")
CMD_HEADER = struct.Struct(">HHHBB")


def can_id(msg_type, node):
    return (msg_type << 4) | node


def _checksum(packet):
    x = 0
    for b in packet:
        x ^= b
    return x ^ 0xFF


def build_command(name, seq=0, **args):
    """Encode a command (e.g. build_command("OBC_SET_MODE", MODE=1)) with a valid checksum."""
    mid, fc, fmt, names = CMD[name]
    payload = struct.pack(fmt, *[args.pop(n, 0) for n in names])
    if args:
        raise KeyError(f"{name}: unknown arguments {sorted(args)}")
    length = CMD_HEADER.size + len(payload) - 7
    raw = bytearray(CMD_HEADER.pack(mid, 0xC000 | (seq & 0x3FFF), length, fc, 0) + payload)
    raw[7] = _checksum(raw)
    return bytes(raw)


def parse_command(data):
    """Decode a command packet; returns (name, args) or raises ValueError."""
    mid, _seq, length, fc, _cks = CMD_HEADER.unpack_from(data)
    if length != len(data) - 7:
        raise ValueError("length field does not match packet size")
    x = 0
    for b in data:
        x ^= b
    if x != 0xFF:
        raise ValueError("bad checksum")
    name = CMD_BY_ID.get((mid, fc))
    if name is None:
        raise ValueError(f"unknown command MID 0x{mid:04X} FC {fc}")
    _mid, _fc, fmt, names = CMD[name]
    return name, dict(zip(names, struct.unpack(fmt, data[CMD_HEADER.size:])))


def build_telemetry(name, seconds=0, subseconds=0, seq=0, **fields):
    """Encode a telemetry packet; missing fields are zero."""
    mid, fmt, names = TLM[name]
    payload = struct.pack(fmt, *[fields.pop(n, b"" if n in STRING_FIELDS.get(name, ()) else 0) for n in names])
    if fields:
        raise KeyError(f"{name}: unknown fields {sorted(fields)}")
    length = TLM_HEADER.size + len(payload) - 7
    return TLM_HEADER.pack(mid, 0xC000 | (seq & 0x3FFF), length, seconds, subseconds, 0) + payload


def parse_telemetry(data):
    """Decode a telemetry packet; returns (name, header dict, fields dict)."""
    mid, seq, length, seconds, subseconds, _spare = TLM_HEADER.unpack_from(data)
    name = TLM_BY_MID.get(mid)
    if name is None:
        raise ValueError(f"unknown telemetry MID 0x{mid:04X}")
    if length != len(data) - 7:
        raise ValueError("length field does not match packet size")
    _mid, fmt, names = TLM[name]
    values = struct.unpack(fmt, data[TLM_HEADER.size:])
    header = {"seq": seq & 0x3FFF, "seconds": seconds, "subseconds": subseconds}
    return name, header, dict(zip(names, values))


def pack_can(name, **fields):
    msg_type, src, fmt, names = CAN[name]
    data = struct.pack(fmt, *[fields.pop(n, 0) for n in names])
    if fields:
        raise KeyError(f"CAN {name}: unknown fields {sorted(fields)}")
    return data


def unpack_can(name, data):
    _type, _src, fmt, names = CAN[name]
    return dict(zip(names, struct.unpack(fmt, data)))
'''


def gen_python(icd):
    o = [f'"""{HEADER_NOTE}"""', "import struct", "",
         f'ICD_VERSION = "{icd["version"]}"', ""]
    for name, e in icd["enums"].items():
        o.append(f"{name.upper()} = {dict(e['values'])!r}")
    o += ["", "# name: (mid, payload struct format, field names)", "TLM = {"]
    strings = {}
    for p in icd["tlm"]:
        fmt, names = py_fmt(p["fields"])
        o.append(f"    {p['name']!r}: (0x{p['mid']:04X}, {fmt!r}, {names!r}),")
        s = [f["name"] for f in p["fields"] if f["type"] == "char"]
        if s:
            strings[p["name"]] = tuple(s)
    o += ["}", "TLM_BY_MID = {v[0]: k for k, v in TLM.items()}",
          f"STRING_FIELDS = {strings!r}", "",
          "# name: (mid, fc, argument struct format, argument names)", "CMD = {"]
    for c in icd["cmds"]:
        fmt, names = py_fmt(c["fields"])
        o.append(f"    {c['name']!r}: (0x{c['mid']:04X}, {c['fc']}, {fmt!r}, {names!r}),")
    o += ["}", "CMD_BY_ID = {(v[0], v[1]): k for k, v in CMD.items()}", "",
          "# name: (type, source node or 'ANY', payload struct format, field names)", "CAN = {"]
    for m in icd["can"]:
        fmt, names = py_fmt(m["fields"])
        o.append(f"    {m['name']!r}: (0x{m['type']:02X}, {m['src']!r}, {fmt!r}, {names!r}),")
    o += ["}", "CAN_BY_TYPE = {v[0]: k for k, v in CAN.items()}"]
    return "\n".join(o) + "\n" + PY_RUNTIME


# ---------------------------------------------------------------------------
# Markdown layout tables
# ---------------------------------------------------------------------------

def md_table(fields, base):
    o = ["| Offset | Size | Field | Type | Units | Description |", "|---|---|---|---|---|---|"]
    for f in fields:
        t = f["type"] + (f"[{f['count']}]" if f["count"] > 1 or f["type"] == "char" else "")
        desc = f.get("desc", "")
        if "enum" in f:
            desc = (desc + f" Enum `{f['enum']}`.").strip()
        o.append(f"| {base + f['offset']} | {f['size']} | `{f['name']}` | {t} | {f.get('units', '')} | {desc} |")
    return o


def gen_markdown(icd):
    o = ["# HITL FlatSat — Byte-Level Layouts", "",
         f"> {HEADER_NOTE}", "",
         f"ICD data version {icd['version']}. Offsets are from the start of the packet (telemetry and commands) "
         "or the start of the CAN data field. Header layouts are in ICD.md §3.", "",
         "## Enumerations", ""]
    for name, e in icd["enums"].items():
        vals = ", ".join(f"`{k}` = {v}" for k, v in e["values"].items())
        o.append(f"- **{name}**: {vals}")
    o += ["", "## Telemetry packets", ""]
    for p in icd["tlm"]:
        o += [f"### `{p['name']}` — MID `0x{p['mid']:04X}`, {p['total_len']} bytes", "", p["desc"], ""]
        o += md_table(p["fields"], TLM_HDR_LEN) + [""]
    o += ["## Commands", ""]
    for c in icd["cmds"]:
        o += [f"### `{c['name']}` — MID `0x{c['mid']:04X}`, FC {c['fc']}, {c['total_len']} bytes", ""]
        o += (md_table(c["fields"], CMD_HDR_LEN) if c["fields"] else ["No arguments."]) + [""]
    o += ["## CAN messages", ""]
    for m in icd["can"]:
        src = "any node" if m["src"] == "ANY" else m["src"]
        ident = f"`0x{m['type'] << 4:03X}` + node" if m["src"] == "ANY" else \
            f"`0x{(m['type'] << 4) | icd['enums']['node']['values'][m['src']]:03X}`"
        period = f"{m['period_ms']} ms" if m["period_ms"] else "event"
        o += [f"### `{m['name']}` — type `0x{m['type']:02X}`, ID {ident}, DLC {m['dlc']}, from {src}, {period}", ""]
        o += md_table(m["fields"], 0) + [""]
    return "\n".join(o)


# ---------------------------------------------------------------------------

OUTPUTS = {
    "firmware/common/include/flatsat_icd.h": gen_c,
    "ground/flatsat_icd.py": gen_python,
    "nos3/components/hil_bridge/gsw/FLATSAT/cmd_tlm/FLATSAT_TLM.txt": gen_cosmos_tlm,
    "nos3/components/hil_bridge/gsw/FLATSAT/cmd_tlm/FLATSAT_CMD.txt": gen_cosmos_cmd,
    "docs/icd/ICD_layouts.md": gen_markdown,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    try:
        icd = load()
    except IcdError as e:
        print(f"ICD error: {e}", file=sys.stderr)
        return 2

    stale = []
    for rel, gen in OUTPUTS.items():
        path = ROOT / rel
        text = gen(icd)
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")

    if stale:
        print("Out of date (run python3 tools/icd_gen.py):\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    if args.check:
        print("generated files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
