#!/usr/bin/env python3
"""Generates the requirements specification and the test procedures from docs/test/verification.yaml.

    python3 tools/test_docs.py           regenerate
    python3 tools/test_docs.py --check   exit 1 if a generated document is out of date

Outputs: docs/requirements/REQUIREMENTS.md, docs/test/TEST_PROCEDURES.md
"""
import argparse
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/test/verification.yaml"
NOTE = "<!-- Generated by tools/test_docs.py from docs/test/verification.yaml: edit that file, not this one. -->"
METHODS = {"T": "Test", "A": "Analysis", "I": "Inspection", "D": "Demonstration"}


def load():
    v = yaml.safe_load(SOURCE.read_text())
    req_ids = {r["id"] for r in v["requirements"]} | {"ENV"}
    seen = set()
    for tc in v["test_cases"]:
        for st in tc["steps"]:
            if st["id"] in seen or not st["id"].startswith(tc["id"] + "."):
                raise SystemExit(f"step {st['id']}: duplicate, or not under {tc['id']}")
            seen.add(st["id"])
            unknown = set(st["reqs"]) - req_ids
            if unknown:
                raise SystemExit(f"step {st['id']}: unknown requirements {sorted(unknown)}")
    return v


def verifying_steps(v, req_id):
    """{test case: [step ids]} for one requirement."""
    out = {}
    for tc in v["test_cases"]:
        ids = [st["id"] for st in tc["steps"] if req_id in st["reqs"]]
        if ids:
            out[tc["id"]] = ids
    return out


def short(ids):
    """TC-08.1, TC-08.2, TC-08.5 -> 08.1-2, 5"""
    return ", ".join(i.split("-", 1)[1] for i in ids)


def gen_requirements(v):
    o = [NOTE, "", "# HITL FlatSat — System Requirements", "",
         "| | |", "|---|---|", "| Document | HITL-FLATSAT-SRS |", f"| Version | {v['version']} |",
         "| Verified by | [Test plan](../test/TEST_PLAN.md), [test procedures](../test/TEST_PROCEDURES.md), "
         "test report (`tools/test_report.py`) |", "",
         "Eight system-level requirements: what the FlatSat must do, each with a measurable pass criterion. "
         "The interfaces they rely on are specified in the [ICD](../icd/ICD.md). The thresholds behind the "
         "attitude requirements are justified in the [ADCS design note](../design/ADCS_DESIGN.md).", "",
         "Verification methods: T test, A analysis, I inspection, D demonstration.", "",
         "## Summary", "", "| ID | Requirement | Methods | Verified by |", "|---|---|---|---|"]
    for r in v["requirements"]:
        by = verifying_steps(v, r["id"])
        o.append(f"| [{r['id']}](#{r['id'].lower()}) | {r['title']} | {', '.join(r['methods'])} | "
                 f"{', '.join(by)} |")
    for r in v["requirements"]:
        o += ["", f"## {r['id']}", "", f"**{r['title']}**", "", r["text"], "",
              f"*Rationale.* {r['rationale']}", "",
              f"*Verification.* {', '.join(METHODS[m] for m in r['methods'])}:", ""]
        for tc_id, ids in verifying_steps(v, r["id"]).items():
            tc = next(t for t in v["test_cases"] if t["id"] == tc_id)
            planned = f" *({tc['status']})*" if tc.get("status") else ""
            o.append(f"- [{tc_id}](../test/TEST_PROCEDURES.md#{tc_id.lower()}) {tc['title']}{planned}: "
                     f"steps {short(ids)}")
    return "\n".join(o) + "\n"


def gen_procedures(v):
    o = [NOTE, "", "# HITL FlatSat — Test Procedures", "",
         "| | |", "|---|---|", "| Document | HITL-FLATSAT-TP |", f"| Version | {v['version']} |",
         "| Plan | [TEST_PLAN.md](TEST_PLAN.md) |", "",
         "Every test case is automated. The steps below are the checks its script makes, in order. Each check "
         "prints `PASS [TC-nn.m]` or `FAIL [TC-nn.m]` followed by the values it measured, and the test report "
         "collects those lines. `tests/run_all.sh` runs all the stages; each case also gives the command to run "
         "it on its own.", "",
         "| Test case | Title | Stage | Steps | Status |", "|---|---|---|---|---|"]
    for tc in v["test_cases"]:
        o.append(f"| [{tc['id']}](#{tc['id'].lower()}) | {tc['title']} | `{tc['stage']}` | {len(tc['steps'])} | "
                 f"{tc.get('status', 'automated')} |")
    for tc in v["test_cases"]:
        o += ["", f"## {tc['id']}", "", f"**{tc['title']}**" + (f" *({tc['status']})*" if tc.get("status") else ""),
              "", tc["objective"], "", f"- **Stage:** `{tc['stage']}`", f"- **Script:** `{tc['script']}`"]
        if tc.get("config"):
            o.append(f"- **Configuration:** {tc['config']}")
        o += ["", "| Step | Check | Pass criterion | Requirements |", "|---|---|---|---|"]
        for st in tc["steps"]:
            o.append(f"| {st['id']} | {st['title']} | {st['criterion']} | {', '.join(st['reqs'])} |")
    return "\n".join(o) + "\n"


OUTPUTS = {"docs/requirements/REQUIREMENTS.md": gen_requirements, "docs/test/TEST_PROCEDURES.md": gen_procedures}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    v = load()
    stale = []
    for rel, gen in OUTPUTS.items():
        path, text = ROOT / rel, gen(v)
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")
    if stale:
        print("Out of date (run python3 tools/test_docs.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
