"""Generated by tools/icd_gen.py from docs/icd/flatsat_icd.yaml. Do not edit."""
import struct

ICD_VERSION = "1.0"

MODE = {'SAFE': 0, 'DETUMBLE': 1, 'SUN_POINT': 2, 'LOW_POWER': 3, 'TEST': 4}
MODE_REASON = {'BOOT': 0, 'COMMAND': 1, 'FAULT': 2, 'AUTO_RATES_HIGH': 3, 'AUTO_CONVERGED': 4, 'LOW_BATTERY': 5, 'NODE_LOST': 6}
RESET_CAUSE = {'POWER_ON': 0, 'WATCHDOG': 1, 'COMMAND': 2, 'UNKNOWN': 3}
SEVERITY = {'DEBUG': 0, 'INFO': 1, 'WARNING': 2, 'ERROR': 3, 'CRITICAL': 4}
TIME_SOURCE = {'FREE_RUNNING': 0, 'UMBILICAL': 1}
ADCS_MODE = {'OFF': 0, 'BDOT': 1, 'SUN_POINT': 2, 'MANUAL': 3}
CHARGE_STATE = {'IDLE': 0, 'CHARGING': 1, 'FULL': 2}
RW_CTRL_MODE = {'OFF': 0, 'SPEED': 1, 'DUTY': 2}
NODE = {'OBC': 1, 'ADCS': 2, 'EPS': 3}
NODE_STATE = {'BOOT': 0, 'NOMINAL': 1, 'SAFE': 2, 'FAULT': 3}
NODE_CMD = {'PING': 1, 'RESET': 2, 'ENTER_SAFE': 3}
SWITCH_STATE = {'OFF': 0, 'ON': 1}

# name: (mid, payload struct format, field names)
TLM = {
    'OBC_HK': (0x0A00, '<IHHHBBBBHBBBBIIHBBHH', ['UPTIME', 'CMD_ACCEPT_COUNT', 'CMD_REJECT_COUNT', 'LAST_CMD_MID', 'LAST_CMD_FC', 'MODE', 'MODE_REASON', 'RESET_CAUSE', 'RESET_COUNT', 'CPU_LOAD', 'NODE_ALIVE_MASK', 'TIME_SOURCE', 'LINK_FLAGS', 'CAN_TX_COUNT', 'CAN_RX_COUNT', 'CAN_ERROR_COUNT', 'CAN_TEC', 'CAN_REC', 'EVENT_COUNT', 'SENSOR_MISSES']),
    'BEACON': (0x0A01, '<IBBHHHHBBHH', ['UPTIME', 'MODE', 'FAULT_FLAGS', 'CMD_ACCEPT_COUNT', 'SIM_BATT_MV', 'REAL_BATT_MV', 'BODY_RATE', 'ECLIPSE', 'NODE_ALIVE_MASK', 'EVENT_COUNT', 'SPARE']),
    'EVENT': (0x0A02, '<HBB64s', ['EVENT_ID', 'SEVERITY', 'SPARE', 'TEXT']),
    'ADCS_STATE': (0x0A10, '<BBBBffffffffffffffffhhhhff', ['ADCS_MODE', 'SUN_VALID', 'CONVERGED', 'SPARE', 'RATE_EST_0', 'RATE_EST_1', 'RATE_EST_2', 'MAG_BODY_0', 'MAG_BODY_1', 'MAG_BODY_2', 'SUN_BODY_0', 'SUN_BODY_1', 'SUN_BODY_2', 'POINTING_ERROR', 'RW_CMD_SPEED_0', 'RW_CMD_SPEED_1', 'RW_CMD_SPEED_2', 'RW_SIM_SPEED_0', 'RW_SIM_SPEED_1', 'RW_SIM_SPEED_2', 'TRQ_DUTY_0', 'TRQ_DUTY_1', 'TRQ_DUTY_2', 'SPARE2', 'PHYS_RW_CMD_SPEED', 'PHYS_RW_MEAS_SPEED']),
    'ADCS_SENSORS': (0x0A11, '<HHfffffffffffffffffffffffffffHHf', ['VALID_MASK', 'SPARE', 'IMU_RATE_0', 'IMU_RATE_1', 'IMU_RATE_2', 'IMU_ACCEL_0', 'IMU_ACCEL_1', 'IMU_ACCEL_2', 'MAG_0', 'MAG_1', 'MAG_2', 'FSS_ALPHA', 'FSS_BETA', 'CSS_0', 'CSS_1', 'CSS_2', 'CSS_3', 'CSS_4', 'CSS_5', 'ST_QUAT_0', 'ST_QUAT_1', 'ST_QUAT_2', 'ST_QUAT_3', 'GPS_POS_ECEF_0', 'GPS_POS_ECEF_1', 'GPS_POS_ECEF_2', 'GPS_VEL_ECEF_0', 'GPS_VEL_ECEF_1', 'GPS_VEL_ECEF_2', 'GPS_WEEK', 'SPARE2', 'GPS_SOW']),
    'EPS_SIM': (0x0A20, '<ffffffffBBH', ['BATT_V', 'BATT_TEMP', 'BUS_3V3', 'BUS_5V0', 'BUS_12V', 'EPS_TEMP', 'SA_V', 'SA_TEMP', 'SWITCH_MASK', 'ECLIPSE', 'SPARE']),
    'EPS_REAL': (0x0A21, '<HHHhhhHHHHhBBBBHI', ['RAIL_MV_0', 'RAIL_MV_1', 'RAIL_MV_2', 'RAIL_MA_0', 'RAIL_MA_1', 'RAIL_MA_2', 'RAIL_MW_0', 'RAIL_MW_1', 'RAIL_MW_2', 'BATT_MV', 'BATT_MA', 'CHARGE_STATE', 'SWITCH_MASK', 'SWITCH_FAULT_MASK', 'EPS_NODE_STATE', 'SPARE', 'EPS_UPTIME']),
    'COMMS_STATS': (0x0A30, '<IIHHhbBHHII', ['RF_TX_FRAMES', 'RF_RX_FRAMES', 'RF_CRC_ERRORS', 'RF_REJECTED', 'LAST_RSSI', 'LAST_SNR', 'CONTACT', 'DUTY_CYCLE', 'TX_QUEUE_DEPTH', 'UMB_TX_PACKETS', 'UMB_RX_PACKETS']),
    'PING_REPLY': (0x0A31, '<IIHH', ['TOKEN', 'RX_SECONDS', 'RX_SUBSECONDS', 'SPARE']),
}
TLM_BY_MID = {v[0]: k for k, v in TLM.items()}
STRING_FIELDS = {'EVENT': ('TEXT',)}

# name: (mid, fc, argument struct format, argument names)
CMD = {
    'OBC_NOOP': (0x1A00, 0, '<', []),
    'OBC_RESET_COUNTERS': (0x1A00, 1, '<', []),
    'OBC_SET_MODE': (0x1A00, 2, '<B', ['MODE']),
    'OBC_SET_TIME': (0x1A00, 3, '<IH', ['SECONDS', 'SUBSECONDS']),
    'OBC_PING': (0x1A00, 4, '<I', ['TOKEN']),
    'OBC_SET_TLM_PERIOD': (0x1A00, 5, '<HH', ['TLM_MID', 'PERIOD']),
    'OBC_DOWNLINK_PACKET': (0x1A00, 6, '<H', ['TLM_MID']),
    'OBC_NODE_RESET': (0x1A00, 7, '<B', ['NODE']),
    'OBC_REBOOT': (0x1A00, 8, '<I', ['MAGIC']),
    'ADCS_NOOP': (0x1A10, 0, '<', []),
    'ADCS_SET_BDOT_GAIN': (0x1A10, 1, '<f', ['GAIN']),
    'ADCS_SET_SUN_GAINS': (0x1A10, 2, '<ff', ['KP', 'KD']),
    'ADCS_RW_MANUAL': (0x1A10, 3, '<BBHf', ['WHEEL', 'SPARE', 'SPARE2', 'SPEED']),
    'ADCS_TRQ_MANUAL': (0x1A10, 4, '<BBh', ['TORQUER', 'SPARE', 'DUTY']),
    'EPS_NOOP': (0x1A20, 0, '<', []),
    'EPS_SWITCH': (0x1A20, 1, '<BB', ['SWITCH_ID', 'STATE']),
    'EPS_SIM_SWITCH': (0x1A20, 2, '<BB', ['SWITCH_ID', 'STATE']),
    'COMMS_NOOP': (0x1A30, 0, '<', []),
    'COMMS_SET_TX_POWER': (0x1A30, 1, '<b', ['POWER']),
    'COMMS_SET_BEACON_PERIOD': (0x1A30, 2, '<H', ['PERIOD']),
}
CMD_BY_ID = {(v[0], v[1]): k for k, v in CMD.items()}

# name: (type, source node or 'ANY', payload struct format, field names)
CAN = {
    'TIME_SYNC': (0x01, 'OBC', '<IH', ['SECONDS', 'SUBSECONDS']),
    'MODE': (0x02, 'OBC', '<BB', ['MODE', 'FLAGS']),
    'FAULT': (0x04, 'ANY', '<BBH', ['CODE', 'DETAIL', 'VALUE']),
    'RW_CMD': (0x10, 'OBC', '<BBhB', ['WHEEL', 'CTRL_MODE', 'SETPOINT', 'SEQ']),
    'RW_TLM': (0x11, 'ADCS', '<BBhhbB', ['WHEEL', 'STATUS', 'SPEED', 'SETPOINT_ECHO', 'DUTY', 'SEQ_ECHO']),
    'EPS_RAIL': (0x20, 'EPS', '<BBHhH', ['RAIL', 'FLAGS', 'VOLTAGE', 'CURRENT', 'POWER']),
    'EPS_BATT': (0x21, 'EPS', '<HhBB', ['VOLTAGE', 'CURRENT', 'CHARGE_STATE', 'FLAGS']),
    'EPS_SW_CMD': (0x28, 'OBC', '<BBB', ['SWITCH_ID', 'STATE', 'SEQ']),
    'EPS_SW_TLM': (0x29, 'EPS', '<BBB', ['STATE_MASK', 'FAULT_MASK', 'SEQ_ECHO']),
    'HEARTBEAT': (0x70, 'ANY', '<IBBBB', ['UPTIME', 'STATE', 'TEC', 'REC', 'RESET_CAUSE']),
    'NODE_CMD': (0x7E, 'OBC', '<BBH', ['TARGET', 'CMD', 'ARG']),
    'NODE_ACK': (0x7F, 'ANY', '<BB', ['CMD', 'RESULT']),
}
CAN_BY_TYPE = {v[0]: k for k, v in CAN.items()}

TLM_HEADER = struct.Struct(">HHHIHI")
CMD_HEADER = struct.Struct(">HHHBB")


def can_id(msg_type, node):
    return (msg_type << 4) | node


def _checksum(packet):
    x = 0
    for b in packet:
        x ^= b
    return x ^ 0xFF


def build_command(name, seq=0, **args):
    """Encode a command (e.g. build_command("OBC_SET_MODE", MODE=1)) with a valid checksum."""
    mid, fc, fmt, names = CMD[name]
    payload = struct.pack(fmt, *[args.pop(n, 0) for n in names])
    if args:
        raise KeyError(f"{name}: unknown arguments {sorted(args)}")
    length = CMD_HEADER.size + len(payload) - 7
    raw = bytearray(CMD_HEADER.pack(mid, 0xC000 | (seq & 0x3FFF), length, fc, 0) + payload)
    raw[7] = _checksum(raw)
    return bytes(raw)


def parse_command(data):
    """Decode a command packet; returns (name, args) or raises ValueError."""
    mid, _seq, length, fc, _cks = CMD_HEADER.unpack_from(data)
    if length != len(data) - 7:
        raise ValueError("length field does not match packet size")
    x = 0
    for b in data:
        x ^= b
    if x != 0xFF:
        raise ValueError("bad checksum")
    name = CMD_BY_ID.get((mid, fc))
    if name is None:
        raise ValueError(f"unknown command MID 0x{mid:04X} FC {fc}")
    _mid, _fc, fmt, names = CMD[name]
    return name, dict(zip(names, struct.unpack(fmt, data[CMD_HEADER.size:])))


def build_telemetry(name, seconds=0, subseconds=0, seq=0, **fields):
    """Encode a telemetry packet; missing fields are zero."""
    mid, fmt, names = TLM[name]
    payload = struct.pack(fmt, *[fields.pop(n, b"" if n in STRING_FIELDS.get(name, ()) else 0) for n in names])
    if fields:
        raise KeyError(f"{name}: unknown fields {sorted(fields)}")
    length = TLM_HEADER.size + len(payload) - 7
    return TLM_HEADER.pack(mid, 0xC000 | (seq & 0x3FFF), length, seconds, subseconds, 0) + payload


def parse_telemetry(data):
    """Decode a telemetry packet; returns (name, header dict, fields dict)."""
    mid, seq, length, seconds, subseconds, _spare = TLM_HEADER.unpack_from(data)
    name = TLM_BY_MID.get(mid)
    if name is None:
        raise ValueError(f"unknown telemetry MID 0x{mid:04X}")
    if length != len(data) - 7:
        raise ValueError("length field does not match packet size")
    _mid, fmt, names = TLM[name]
    values = struct.unpack(fmt, data[TLM_HEADER.size:])
    header = {"seq": seq & 0x3FFF, "seconds": seconds, "subseconds": subseconds}
    return name, header, dict(zip(names, values))


def pack_can(name, **fields):
    msg_type, src, fmt, names = CAN[name]
    data = struct.pack(fmt, *[fields.pop(n, 0) for n in names])
    if fields:
        raise KeyError(f"CAN {name}: unknown fields {sorted(fields)}")
    return data


def unpack_can(name, data):
    _type, _src, fmt, names = CAN[name]
    return dict(zip(names, struct.unpack(fmt, data)))
